name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *" # Har 5 minute mein trigger hoga
  workflow_dispatch: # Agar manual button dabana ho kabhi

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping StudyOrbit API
        run: curl -s https://studyorbit-backend-0chi.onrender.com/api/health